### ISSUE TITLE
Windows builds compiled with the MKL

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/scikit-image-feedstock#24]
It seems that the windows builds are compiled with numpy and the MKL. Is that OK?

See: https://ci.appveyor.com/project/conda-forge/scikit-image-feedstock/branch/master/job/5330nhxy3d2giycj#L254

Is there a way to specify numpy from conda-forge and not defaults in the meta.yml

**Comment by mcs07** [comment]
I think the issue is that there is no conda-forge SciPy built with openblas on Windows (yet). See https://github.com/conda-forge/scipy-feedstock/pull/78

**Comment by jakirkham** [comment]
Don't think this should matter as long as `scikit-image` is not directly linking to the BLAS, which doesn't appear to be the case. To contrast, this is something we do need to keep track of with `scikit-learn`.

**Comment by hmaarrfk** [comment]
Got it, thanks!
