### ISSUE TITLE
Weird issues building on windows 

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/scikit-image-feedstock#26]
https://github.com/conda-forge/scikit-image-feedstock/blob/6d9699ec37588391450d04f6a116701f0d375c0a/recipe/meta.yaml#L22

with that line as is, my windows builds fail 1/2 the time. Using single quotes seem to be more consistent. Just letting people know in case they run into this issue themselves.

maybe this is an ok fix?
```
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

**Comment by jni** [comment]
ping @jakirkham have you seen this issue before?

**Comment by jakirkham** [comment]
Changing the quotes have an effect is pretty surprising. These get parsed by Jinja in the conda-build rendering phase and have no impact on the build after that. So expect this is a red herring and something else is causing build issues.

Would be helpful to get some more information so we can understand the issue. How is it being built? How does it fail for instance? Is there a log that can be posted here (even a small snippet around the failure would be useful)? What version of Windows is involved? Versions of tools being using (`conda info` should do nicely)? What Python versions are involved? Anything else that you can think of that might be helpful for debugging?

**Comment by hmaarrfk** [comment]
Here is an appveyor log. I'll try to create a fresh build soon when I get access to a power source

This is an example of the error.
https://ci.appveyor.com/project/hmaarrfk/scikit-image-feedstock/build/1.0.2/job/rpyb39797c00oc4n#L1031
That said, I added
```
 - m2-patch  # [win]
```
to that build

Here is a freshly triggered build
https://ci.appveyor.com/project/hmaarrfk/scikit-image-feedstock/build/1.0.9
Maybe it will reproduce the issue.

**Comment by jni** [comment]
> `failed with error code 3221225477`

Well, isn't it obvious from that what the problem is??? =P

**Comment by jakirkham** [comment]
So the syntax for building has changed a bit with `conda-build` 3. Namely `conda-build` 3 has [variants]( https://conda.io/docs/user-guide/tasks/build-packages/variants.html#build-variants ). This is how the `compiler` syntax is configured. It is also how we configure things like which `python` version to build against or really any version constraints we might see appropriate.

For instance, to build for Python 3.6, one runs the command below. Here's the [variant file]( https://github.com/conda-forge/scikit-image-feedstock/blob/master/.ci_support/win_c_compilervs2015cxx_compilervs2015python3.6.yaml ) that one uses for this. Nothing too complicated as far as `scikit-image` is concerned. That said, not specifying this file might cause problems.

```batch
conda build recipe -m .ci_support\win_c_compilervs2015cxx_compilervs2015python3.6.yaml
```

**Comment by jakirkham** [comment]
The build that you linked above is complaining about `inttypes.h` not being present. It's also building with Visual Studio 2008 (Python 2.7), which did not have `inttypes.h`. Normally we workaround this issue by placing a copy of `inttypes.h` in a place where the compiler can find it. We do this by requiring `msinttypes` in the `host` prefix for that Visual Studio version specifically, which we seem to be doing here currently. Not totally sure why Visual Studio is not finding it some of the time. 🤔

**Comment by hmaarrfk** [comment]
@jakirkham I'll try to run things with the variant specified. That seems important!

Re the appveyork link: I really thought it was 3.6 that was being built. The sister build [with MSV2015](https://ci.appveyor.com/project/hmaarrfk/scikit-image-feedstock/build/1.0.2/job/m864vsmo7mlkuk9w) also failed the same way.
and regarding removing msinttypes, when working on my computer locally 4 hours ago, I was just using the branch `master_redux` where I only changed the build number to trigger a build on the CI's. I hadn't removed msinttypes.

I would have tried it again, but windows decided to BSOD, letting me know it was time to sleep.

**Comment by hmaarrfk** [comment]
I think my original issues are resolved. I've been building scikit-image fine these days. Well except for the more recent issue.
