### ISSUE TITLE
Should scikit-image link against LLVM OpenMP instead of GNU OpenMP

### ISSUE THREAD

**Issue by knedlsepp** [conda-forge/scikit-image-feedstock#69]
Issue:
I don't have a minimal reproducer for this but I have the suspicion that linking against GNU OpenMP might the same undesired effects in scikit-image as was observed and fixed for OpenBLAS here: https://github.com/conda-forge/openblas-feedstock/pull/92 

I'm thus wondering if an equivalent change should also be made here.

Ping @beckermr

**Comment by knedlsepp** [comment]
Similar issue for scikit-learn: https://github.com/conda-forge/scikit-learn-feedstock/issues/136

**Comment by hmaarrfk** [comment]
I don't think we explicitely link to either of them.

**Comment by hmaarrfk** [comment]
You should be able to switch in your environment
https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=openmp#openmp

**Comment by knedlsepp** [comment]
Ah. I wasn't aware of that. It's somehow confusing me however then that the openblas-feedstock explicitly mentions `llvm-openmp` as a build dependency when they could use the same mechanism. :thinking:

**Comment by hmaarrfk** [comment]
I'm really not sure, this stuff confuses me as well.

But if you are trying to hunt a bug that is affecting you, i wanted to point you in the right direction.
